version: '3.8'

services:
  web:
    image: alphadev224/blog
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog224
      POSTGRES_DB_NAME: blog


volumes:
  postgres_data:
